name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: gradle

    - name: make .env
      run: |
        touch .env
        echo "${{ secrets.ENV }}" >> ./.env
      shell: bash

    - name: make application.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" >> ./application.properties
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Docker image build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/view-app:latest .

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/view-app:latest

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5
